apiVersion: v1
appVersion: 0.0.1
name: {APP-NAME}
description: A Helm chart for {APP-NAME}
engine: gotpl
home: https://github.com/giantswarm/{APP-NAME}-app

# If you have an icon/logo, you should add it to https://github.com/giantswarm/web-assets
# and set the final URL as a value here and uncomment.
#icon: https://s.giantswarm.io/app-icons/example-app/1/light.svg

sources:
- https://github.com/some-org/some-repo
version: 0.1.0 # [[ .Version ]] if you're using architect instead of app-build-suite
annotations:
  branch: my-branch # Used through .Chart.Annotations.branch (This is not replaced automatically)
  commit: f00bar # Used through .Chart.Annotations.commit (This is not replaced automatically)
