apiVersion: v2
name: security-bundle
description: A Helm chart for Giant Swarm's collection of open-source security tools.
icon: https://s.giantswarm.io/app-icons/giantswarm/1/dark.svg
engine: gotpl
home: https://github.com/giantswarm/security-bundle
sources:
  - https://github.com/giantswarm/security-bundle
version: 0.14.1
annotations:
  application.giantswarm.io/in-cluster-app: "true"
  application.giantswarm.io/team: "shield"
  application.giantswarm.io/app-type: "bundle"
