apiVersion: v2
name: security-pack
description: A Helm chart for Giant Swarm's collection of open-source security tools.
engine: gotpl
home: https://github.com/giantswarm/security-pack
sources:
  - https://github.com/giantswarm/security-pack
version: 0.8.0
annotations:
  application.giantswarm.io/in-cluster-app: "true"
  application.giantswarm.io/team: "shield"
  application.giantswarm.io/app-type: "bundle"
---
apiVersion: v2
name: security-bundle
description: A Helm chart for Giant Swarm's collection of open-source security tools.
engine: gotpl
home: https://github.com/giantswarm/security-pack
sources:
  - https://github.com/giantswarm/security-pack
version: 0.8.0
annotations:
  application.giantswarm.io/in-cluster-app: "true"
  application.giantswarm.io/team: "shield"
  application.giantswarm.io/app-type: "bundle"
