clusterName: ""
organization: ""

userConfig:
  trivy:
    configMap:
      values: |
        trivy:
          networkPolicy:
            enabled: true

apps:
  falco:
    appName: falco
    chartName: falco
    catalog: giantswarm
    enabled: false
    namespace: security-pack
    version: 0.2.0

  kyverno:
    appName: kyverno
    chartName: kyverno
    catalog: giantswarm
    enabled: false
    namespace: security-pack
    version: 0.8.0

  starboard:
    appName: starboard
    chartName: starboard-app
    catalog: giantswarm
    enabled: true
    namespace: security-pack
    version: 0.5.2

  starboardExporter:
    appName: starboard-exporter
    chartName: starboard-exporter
    catalog: giantswarm
    enabled: true
    namespace: security-pack
    version: 0.3.0

  trivy:
    appName: trivy
    chartName: trivy-app
    catalog: giantswarm
    enabled: true
    namespace: security-pack
    version: 0.1.0
