apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $.Values.clusterID }}-migrate-security-apps
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "labels.common" $ | nindent 4 }}
  annotations:
    helm.sh/hook: pre-upgrade
    helm.sh/hook-weight: "-20"
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ $.Values.clusterID }}-migrate-security-apps
subjects:
- kind: ServiceAccount
  name: {{ $.Values.clusterID }}-migrate-security-apps
  namespace: {{ $.Release.Namespace }}
